---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "crawlerx_helm.fullname" . }}-web-app-configs
data:
  VUE_APP_FIREBASE_API_KEY: {{ .Values.crawlerx.env.webApp.VUE_APP_FIREBASE_API_KEY }}
  VUE_APP_FIREBASE_AUTH_DOMAIN: {{ .Values.crawlerx.env.webApp.VUE_APP_FIREBASE_AUTH_DOMAIN }}
  VUE_APP_FIREBASE_DB_DOMAIN: {{ .Values.crawlerx.env.webApp.VUE_APP_FIREBASE_DB_DOMAIN }}
  VUE_APP_FIREBASE_PROJECT_ID: {{ .Values.crawlerx.env.webApp.VUE_APP_FIREBASE_PROJECT_ID }}
  VUE_APP_FIREBASE_STORAGE_BUCKET: {{ .Values.crawlerx.env.webApp.VUE_APP_FIREBASE_STORAGE_BUCKET }}
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID: {{ .Values.crawlerx.env.webApp.VUE_APP_FIREBASE_MESSAGING_SENDER_ID | quote }}
  VUE_APP_FIREBASE_APP_ID: {{ .Values.crawlerx.env.webApp.VUE_APP_FIREBASE_APP_ID}}
  VUE_APP_FIREBASE_MEASURMENT_ID: {{ .Values.crawlerx.env.webApp.VUE_APP_FIREBASE_MEASURMENT_ID }}
  VUE_APP_DJANGO_PROTOCOL: {{ .Values.crawlerx.env.webApp.VUE_APP_DJANGO_PROTOCOL }}
  VUE_APP_DJANGO_HOSTNAME: {{ include "crawlerx_helm.fullname" . }}-backend-service
  VUE_APP_DJANGO_PORT: {{ .Values.crawlerx.env.webApp.VUE_APP_DJANGO_PORT | quote }}
