apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawlerx_helm.fullname" . }}-web-app-service
  namespace : {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - name: http  
    port: {{ .Values.crawlerx.ingress.webApp.service.servicePort }}
  selector:
    app: "{{ include "crawlerx_helm.fullname" . }}-web-app-selector"
