{{- $username := .Values.crawlerx.subscription.username }}
{{- $password := .Values.crawlerx.subscription.password }}
{{- $email := .Values.crawlerx.subscription.username }}
{{- $regId := default "docker.io" .Values.crawlerx.deployment.webApp.dockerRegistry }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
{{- $files := .Files }}
apiVersion: v1
kind: Secret
metadata:
  name: crawlerx-deployment-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $files.Get "auth.json" | replace "reg.id" $regId | replace "reg.username" $username | replace "reg.password" $password | replace "reg.email" $email | replace "reg.auth" $auth | b64enc }}
{{ end }}