dependencies:
  - name: mongodb
    version: "10.21.2"
    repository: "https://charts.bitnami.com/bitnami"
  - name: rabbitmq
    version: "8.16.3"
    repository: "https://charts.bitnami.com/bitnami"  
  - name: elasticsearch
    version: "7.8.1"
    repository: "https://helm.elastic.co"   