apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawlerx_helm.fullname" . }}-celery-worker-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.crawlerx.deployment.celery.worker.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.crawlerx.deployment.celery.strategy.rollingUpdate.maxSurge }}
      maxSurge: {{ .Values.crawlerx.deployment.celery.strategy.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: {{ include "crawlerx_helm.fullname" . }}-celery-worker-selector
      version: "current"
  template:
    metadata:
      labels:
        app: {{ include "crawlerx_helm.fullname" . }}-celery-worker-selector
        version: "current"
    spec:
      containers:
      - name: "crawlerx_celery_worker_appication"
        {{- if .Values.crawlerx.deployment.celery.dockerRegistry }}
        image: "{{ .Values.crawlerx.deployment.celery.dockerRegistry }}/{{ .Values.crawlerx.deployment.celery.imageName }}:{{ .Values.crawlerx.deployment.celery.imageTag }}"
        {{- else }}
        image: "{{ .Values.crawlerx.deployment.celery.imageName }}:{{ .Values.crawlerx.deployment.celery.imageTag }}"
        {{ end }}
        command: ["python3", '-m', "celery", "-A", "crawlerx_server", "worker", "-l", "info"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.crawlerx.deployment.celery.resources.requests.memory }}
            cpu: {{ .Values.crawlerx.deployment.celery.resources.requests.cpu }}
          limits:
            memory: {{ .Values.crawlerx.deployment.celery.resources.limits.memory }}
            cpu: {{ .Values.crawlerx.deployment.celery.resources.limits.cpu }}
        {{- if .Values.crawlerx.deployment.celery.envs }}
        env:
          {{- range $key, $val := .Values.crawlerx.deployment.celery.envs }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "crawlerx_helm.fullname" . }}-celery-configs
        {{- if .Values.crawlerx.deployment.celery.imagePullSecrets }}  
        imagePullSecrets:
          - name: {{ .Values.crawlerx.deployment.celery.imagePullSecrets }}
        {{- else if and (not (eq .Values.crawlerx.subscription.username "")) (not (eq .Values.crawlerx.subscription.password "")) }}
        imagePullSecrets:
          - name: crawlerx-deployment-secret
        {{ end }}  
