---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "crawlerx_helm.fullname" . }}-backend-configs
data:
  MONGODB_URL: {{ include "crawlerx_helm.fullname" . }}-mongodb-service
  RABBITMQ_URL: {{ include "crawlerx_helm.fullname" . }}-rabbitmq-service
