apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawlerx_helm.fullname" . }}-backend-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.crawlerx.deployment.backend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.crawlerx.deployment.backend.strategy.rollingUpdate.maxSurge }}
      maxSurge: {{ .Values.crawlerx.deployment.backend.strategy.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: {{ include "crawlerx_helm.fullname" . }}-backend-selector
      version: "current"
  template:
    metadata:
      labels:
        app: {{ include "crawlerx_helm.fullname" . }}-backend-selector
        version: "current"
    spec:
      initContainers:
        - name: init-mongodb
          image: busybox:1.32
          command: ['sh', '-c', 'echo -e "Checking for the availability of MongoDB deployment"; while ! nc -z {{ .Values.mongodb.service.nameOverride }} 27017; do sleep 1; printf "-"; done; echo -e "  >> MongoDB has started";']
        - name: init-elasticsearch
          image: busybox:1.32
          command: ['sh', '-c', 'echo -e "Checking for the availability of Elasticsearch deployment"; while ! nc -z {{ .Values.elasticsearch.masterService }} 9200; do sleep 1; printf "-"; done; echo -e "  >> Elasticsearch has started";']
      containers:
        - name: "crawlerx-django-appication"
          {{- if .Values.crawlerx.deployment.backend.dockerRegistry }}
          image: "{{ .Values.crawlerx.deployment.backend.dockerRegistry }}/{{ .Values.crawlerx.deployment.backend.imageName }}:{{ .Values.crawlerx.deployment.backend.imageTag }}"
          {{- else }}
          image: "{{ .Values.crawlerx.deployment.backend.imageName }}:{{ .Values.crawlerx.deployment.backend.imageTag }}"
          {{ end }}
          command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          resources:
            requests:
              memory: {{ .Values.crawlerx.deployment.backend.resources.requests.memory }}
              cpu: {{ .Values.crawlerx.deployment.backend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.crawlerx.deployment.backend.resources.limits.memory }}
              cpu: {{ .Values.crawlerx.deployment.backend.resources.limits.cpu }}
          {{- if .Values.crawlerx.deployment.backend.envs }}
          env:
            {{- range $key, $val := .Values.crawlerx.deployment.backend.envs }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "crawlerx_helm.fullname" . }}-backend-configs
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 8000
            initialDelaySeconds: {{ .Values.crawlerx.deployment.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.crawlerx.deployment.backend.livenessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 8000
            initialDelaySeconds: {{ .Values.crawlerx.deployment.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.crawlerx.deployment.backend.readinessProbe.periodSeconds }}
      {{- if .Values.crawlerx.deployment.backend.imagePullSecrets }}  
      imagePullSecrets:
        - name: {{ .Values.crawlerx.deployment.backend.imagePullSecrets }}
      {{- else if and (not (eq .Values.crawlerx.subscription.username "")) (not (eq .Values.crawlerx.subscription.password "")) }}
      imagePullSecrets:
        - name: crawlerx-deployment-secret
      {{ end }}  
