apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawlerx_helm.fullname" . }}-backend-service
  namespace : {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - name: http  
    port: 8000
  selector:
    app: "{{ include "crawlerx_helm.fullname" . }}-backend-selector"
