apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawlerx_helm.fullname" . }}-scrapy-service
  namespace : {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - name: http  
    port: 6800
    targetPort: 6800
    protocol: TCP
  selector:
    app: "{{ include "crawlerx_helm.fullname" . }}-scrapy-selector"
